In [33]:
import numpy as np

In [43]:
fo = open('Problem11_data.txt', 'r')

lines = []
for line in fo:
    data = str(line).rstrip().split(' ')
    arr = np.asarray(data, dtype=np.int64)
    lines.append(arr)

arr = np.stack(lines)
print(arr)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93

In [61]:
high = 0
for xi in range(20):
    for yi in range(20):
        # Down sequence
        print('Head: %d,%d' % (xi,yi))
        if xi + 3 < 20:
            p0, p1, p2, p3 = arr[xi,yi], arr[xi+1,yi], arr[xi+2,yi], arr[xi+3,yi]
            product_down = p0 * p1 * p2 * p3
            print('down %d * %d * %d * %d = %d' % (p0, p1, p2, p3, product_down))
        if yi + 3 < 20:
            p0, p1, p2, p3 = arr[xi,yi], arr[xi,yi+1], arr[xi,yi+2], arr[xi,yi+3]
            product_right = p0 * p1 * p2 * p3
            print('rght %d * %d * %d * %d = %d' % (p0, p1, p2, p3, product_right))
        if xi + 3 < 20 and yi + 3 < 20:
            p0, p1, p2, p3 = arr[xi,yi], arr[xi+1,yi+1], arr[xi+2,yi+2], arr[xi+3,yi+3]
            product_right_diag = p0 * p1 * p2 * p3
            print('diagr %d * %d * %d * %d = %d\n' % (p0, p1, p2, p3, product_right_diag))
        if xi + 3 < 20 and yi - 3 >= 0:
            p0, p1, p2, p3 = arr[xi,yi], arr[xi+1,yi-1], arr[xi+2,yi-2], arr[xi+3,yi-3]
            product_left_diag = p0 * p1 * p2 * p3
            print('diagl %d * %d * %d * %d = %d\n' % (p0, p1, p2, p3, product_left_diag))
        highest = max([product_down, product_right, product_right_diag, product_left_diag])
        if highest > high:
            high = highest

Head: 0,0
down 8 * 49 * 81 * 52 = 1651104
rght 8 * 2 * 22 * 97 = 34144
diagr 8 * 49 * 31 * 23 = 279496

Head: 0,1
down 2 * 49 * 49 * 70 = 336140
rght 2 * 22 * 97 * 38 = 162184
diagr 2 * 99 * 73 * 4 = 57816

Head: 0,2
down 22 * 99 * 31 * 95 = 6414210
rght 22 * 97 * 38 * 15 = 1216380
diagr 22 * 40 * 55 * 60 = 2904000

Head: 0,3
down 97 * 40 * 73 * 23 = 6514520
rght 97 * 38 * 15 * 0 = 0
diagr 97 * 17 * 79 * 11 = 1432981

diagl 97 * 99 * 49 * 52 = 24468444

Head: 0,4
down 38 * 17 * 55 * 4 = 142120
rght 38 * 15 * 0 * 40 = 0
diagr 38 * 81 * 14 * 42 = 1809864

diagl 38 * 40 * 31 * 70 = 3298400

Head: 0,5
down 15 * 81 * 79 * 60 = 5759100
rght 15 * 0 * 40 * 0 = 0
diagr 15 * 18 * 29 * 69 = 540270

diagl 15 * 17 * 73 * 95 = 1768425

Head: 0,6
down 0 * 18 * 14 * 11 = 0
rght 0 * 40 * 0 * 75 = 0
diagr 0 * 57 * 93 * 24 = 0

diagl 0 * 81 * 55 * 23 = 0

Head: 0,7
down 40 * 57 * 29 * 42 = 2777040
rght 40 * 0 * 75 * 4 = 0
diagr 40 * 60 * 71 * 68 = 11587200

diagl 40 * 18 * 79 * 4 = 227520

Head: 0,8
down

In [62]:
print(high)

70600674
