In [41]:
import numpy as np

arr = [[  7, 53,183,439,863],
       [497,383,563, 79,973],
       [287, 63,343,169,583],
       [627,343,773,959,943],
       [767,473,103,699,303]]

arr = np.asarray(arr)
arr2 = np.zeros(arr.shape)

In [44]:
print(arr)
print(arr2)

[[  7  53 183 439 863]
 [497 383 563  79 973]
 [287  63 343 169 583]
 [627 343 773 959 943]
 [767 473 103 699 303]]
[[-3723. -2807. -3327. -3451. -4347.]
 [-4183. -3427. -3897. -4761. -5187.]
 [-3343. -2697. -3067. -3621. -4527.]
 [-5203. -4617. -4837. -5031. -6367.]
 [-3763. -3187. -4207. -3991. -5707.]]


In [43]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        col_sum = np.sum(arr[i,:])
        row_sum = np.sum(arr[:,j])
        all_sum = col_sum + row_sum
        arr2[i,j] = arr[i,j] - all_sum

In [39]:
msum = 0
while True:
    i,j = np.where(arr2 == np.min(arr2))
    i,j = i[0],j[0]
    msum += arr[i,j]
    print(arr)
    arr2[i,:] = 0
    arr2[:,j] = 0
    if np.sum(arr2) == 0:
        break
print(msum)

[[  7  53 183 439 863]
 [497 383 563  79 973]
 [287  63 343 169 583]
 [627 343 773 959 943]
 [767 473 103 699 303]]
[[  7  53 183 439 863]
 [497 383 563  79 973]
 [287  63 343 169 583]
 [627 343 773 959 943]
 [767 473 103 699 303]]
[[  7  53 183 439 863]
 [497 383 563  79 973]
 [287  63 343 169 583]
 [627 343 773 959 943]
 [767 473 103 699 303]]
[[  7  53 183 439 863]
 [497 383 563  79 973]
 [287  63 343 169 583]
 [627 343 773 959 943]
 [767 473 103 699 303]]
[[  7  53 183 439 863]
 [497 383 563  79 973]
 [287  63 343 169 583]
 [627 343 773 959 943]
 [767 473 103 699 303]]
1195
